/*
* "Student Projects in Motion" — index.php:2826-2891: the `.grid-gallery-flex` wall with the
 * `.insta-text.isdi-2` caption (transparent, a 6px #ec1376 rule under it) instead of the pink chip.
 */
export const isdiBdesProductProjects = {
  heading: 'Student Projects in Motion',
  sub: 'Where creativity meets momentum',
  columns: [
    [
      {
        image: {
          src: '/assets/images/schools/isdi/programs/b-des/product-design/projects/dia.webp',
          width: 292,
          height: 520,
          alt: '',
        },
        text: 'Dia and Vallen',
        captionVariant: 'isdi-2',
        looseCaption: false,
        bottom16: false,
        topSet: false,
      },
      {
        image: {
          src: '/assets/images/schools/isdi/programs/b-des/product-design/projects/shivika.png',
          width: 292,
          height: 163,
          alt: '',
        },
        text: 'Shivika Shetty',
        captionVariant: 'isdi-2',
        looseCaption: false,
        bottom16: false,
        topSet: true,
      },
      {
        image: {
          src: '/assets/images/schools/isdi/programs/b-des/product-design/projects/arya.webp',
          width: 292,
          height: 520,
          alt: '',
        },
        text: 'Anjali Lalwani',
        captionVariant: 'isdi-2',
        looseCaption: false,
        bottom16: false,
        topSet: true,
      },
      {
        image: {
          src: '/assets/images/schools/isdi/programs/b-des/product-design/projects/sarthak.webp',
          width: 292,
          height: 163,
          alt: '',
        },
        text: 'Sarthak, Saumya, Shane',
        captionVariant: 'isdi-2',
        looseCaption: false,
        bottom16: false,
        topSet: true,
      },
    ],
    [
      {
        image: {
          src: '/assets/images/schools/isdi/programs/b-des/product-design/projects/amvisha.webp',
          width: 299,
          height: 308,
          alt: '',
        },
        text: 'Amvisha Jha',
        captionVariant: 'isdi-2',
        looseCaption: false,
        bottom16: false,
        topSet: false,
      },
      {
        image: {
          src: '/assets/images/schools/isdi/programs/b-des/product-design/projects/abhijay.webp',
          width: 292,
          height: 383,
          alt: '',
        },
        text: 'Abhijay, Amtoj, Aryan',
        captionVariant: 'isdi-2',
        looseCaption: false,
        bottom16: false,
        topSet: false,
      },
      {
        image: {
          src: '/assets/images/schools/isdi/programs/b-des/product-design/projects/tanya.webp',
          width: 292,
          height: 301,
          alt: '',
        },
        text: 'Tanya Jain',
        captionVariant: 'isdi-2',
        looseCaption: false,
        bottom16: false,
        topSet: false,
      },
      {
        image: {
          src: '/assets/images/schools/isdi/programs/b-des/product-design/projects/amtoj.webp',
          width: 292,
          height: 383,
          alt: '',
        },
        text: 'Amtoj S. Nagi',
        captionVariant: 'isdi-2',
        looseCaption: false,
        bottom16: false,
        topSet: false,
      },
    ],
    [
      {
        image: {
          src: '/assets/images/schools/isdi/programs/b-des/product-design/projects/pearl.png',
          width: 293,
          height: 163,
          alt: '',
        },
        text: 'Rutu Sankhe, Shane Bana',
        captionVariant: 'isdi-2',
        looseCaption: false,
        bottom16: true,
        topSet: false,
      },
      {
        image: {
          src: '/assets/images/schools/isdi/programs/b-des/product-design/projects/aashi.webp',
          width: 292,
          height: 520,
          alt: '',
        },
        text: 'Aashi. A, Bageshree. S',
        captionVariant: 'isdi-2',
        looseCaption: false,
        bottom16: false,
        topSet: false,
      },
      {
        image: {
          src: '/assets/images/schools/isdi/programs/b-des/product-design/projects/nishikadesai.png',
          width: 293,
          height: 163,
          alt: '',
        },
        text: 'Nishika Desai',
        captionVariant: 'isdi-2',
        looseCaption: false,
        bottom16: false,
        topSet: false,
      },
      {
        image: {
          src: '/assets/images/schools/isdi/programs/b-des/product-design/projects/krishna.webp',
          width: 292,
          height: 520,
          alt: '',
        },
        text: 'Ayushi Shah',
        captionVariant: 'isdi-2',
        looseCaption: false,
        bottom16: false,
        topSet: false,
      },
    ],
    [
      {
        image: {
          src: '/assets/images/schools/isdi/programs/b-des/product-design/projects/pd-student-work-l-1.webp',
          width: 292,
          height: 364,
          alt: '',
        },
        text: 'Mihir Mehta, Prayushi',
        captionVariant: 'isdi-2',
        looseCaption: true,
        bottom16: false,
        topSet: false,
      },
      {
        image: {
          src: '/assets/images/schools/isdi/programs/b-des/product-design/projects/mansi.webp',
          width: 293,
          height: 319,
          alt: '',
        },
        text: 'Niharika Kondraganti',
        captionVariant: 'isdi-2',
        looseCaption: false,
        bottom16: false,
        topSet: false,
      },
      {
        image: {
          src: '/assets/images/schools/isdi/programs/b-des/product-design/projects/pranjal.webp',
          width: 292,
          height: 364,
          alt: '',
        },
        text: 'Pranjal Pranigrahi',
        captionVariant: 'isdi-2',
        looseCaption: false,
        bottom16: false,
        topSet: false,
      },
      {
        image: {
          src: '/assets/images/schools/isdi/programs/b-des/product-design/projects/crystal.webp',
          width: 293,
          height: 319,
          alt: '',
        },
        text: 'Crystal Prince',
        captionVariant: 'isdi-2',
        looseCaption: false,
        bottom16: false,
        topSet: false,
      },
    ],
  ],
};
