/*
* "Student Projects in Motion" — index.php:2826-2891: the `.grid-gallery-flex` wall with the
 * `.insta-text.isdi-2` caption (transparent, a 6px #ec1376 rule under it) instead of the pink chip.
 */
export const isdiBdesFashionCommProjects = {
  heading: 'Student Projects in Motion',
  sub: 'Where creativity meets momentum',
  columns: [
    [
      {
        image: {
          src: '/assets/images/schools/isdi/programs/b-des/fashion-communication-styling/projects/fashion.webp',
          width: 292,
          height: 520,
          alt: '',
        },
        text: 'Sakshi Lakhani',
        captionVariant: 'isdi-2',
        looseCaption: false,
        bottom16: false,
        topSet: false,
      },
      {
        image: {
          src: '/assets/images/schools/isdi/programs/b-des/fashion-communication-styling/projects/nabharane.png',
          width: 292,
          height: 163,
          alt: '',
        },
        text: 'Nabha Rane',
        captionVariant: 'isdi-2',
        looseCaption: false,
        bottom16: false,
        topSet: true,
      },
      {
        image: {
          src: '/assets/images/schools/isdi/programs/b-des/fashion-communication-styling/projects/girlatulya.webp',
          width: 292,
          height: 520,
          alt: '',
        },
        text: 'Atulya Manishankar',
        captionVariant: 'isdi-2',
        looseCaption: false,
        bottom16: false,
        topSet: true,
      },
      {
        image: {
          src: '/assets/images/schools/isdi/programs/b-des/fashion-communication-styling/projects/ginavongeyer.webp',
          width: 292,
          height: 163,
          alt: '',
        },
        text: 'Gina Vongeyer',
        captionVariant: 'isdi-2',
        looseCaption: false,
        bottom16: false,
        topSet: true,
      },
    ],
    [
      {
        image: {
          src: '/assets/images/schools/isdi/programs/b-des/fashion-communication-styling/projects/ordinary.webp',
          width: 299,
          height: 308,
          alt: '',
        },
        text: 'Mahak Jain and group',
        captionVariant: 'isdi-2',
        looseCaption: false,
        bottom16: false,
        topSet: false,
      },
      {
        image: {
          src: '/assets/images/schools/isdi/programs/b-des/fashion-communication-styling/projects/only2.webp',
          width: 292,
          height: 383,
          alt: '',
        },
        text: 'Mannat Desai, Sanya K',
        captionVariant: 'isdi-2',
        looseCaption: false,
        bottom16: false,
        topSet: false,
      },
      {
        image: {
          src: '/assets/images/schools/isdi/programs/b-des/fashion-communication-styling/projects/imgatt.webp',
          width: 292,
          height: 301,
          alt: '',
        },
        text: 'Aarushi NC',
        captionVariant: 'isdi-2',
        looseCaption: false,
        bottom16: false,
        topSet: false,
      },
      {
        image: {
          src: '/assets/images/schools/isdi/programs/b-des/fashion-communication-styling/projects/123.webp',
          width: 292,
          height: 383,
          alt: '',
        },
        text: 'Atulya Manishankar',
        captionVariant: 'isdi-2',
        looseCaption: false,
        bottom16: false,
        topSet: false,
      },
    ],
    [
      {
        image: {
          src: '/assets/images/schools/isdi/programs/b-des/fashion-communication-styling/projects/fashion311.webp',
          width: 293,
          height: 163,
          alt: '',
        },
        text: 'Celina Jagtiani,',
        captionVariant: 'isdi-2',
        looseCaption: false,
        bottom16: true,
        topSet: false,
      },
      {
        image: {
          src: '/assets/images/schools/isdi/programs/b-des/fashion-communication-styling/projects/ananya.webp',
          width: 292,
          height: 520,
          alt: '',
        },
        text: 'Ananya Pillai',
        captionVariant: 'isdi-2',
        looseCaption: false,
        bottom16: false,
        topSet: false,
      },
      {
        image: {
          src: '/assets/images/schools/isdi/programs/b-des/fashion-communication-styling/projects/kareenadusseja.webp',
          width: 293,
          height: 163,
          alt: '',
        },
        text: 'Kareena Dusseja',
        captionVariant: 'isdi-2',
        looseCaption: false,
        bottom16: false,
        topSet: false,
      },
      {
        image: {
          src: '/assets/images/schools/isdi/programs/b-des/fashion-communication-styling/projects/only.webp',
          width: 292,
          height: 520,
          alt: '',
        },
        text: 'Mannat Desai, Sanya',
        captionVariant: 'isdi-2',
        looseCaption: false,
        bottom16: false,
        topSet: false,
      },
    ],
    [
      {
        image: {
          src: '/assets/images/schools/isdi/programs/b-des/fashion-communication-styling/projects/fcs.webp',
          width: 292,
          height: 364,
          alt: '',
        },
        text: 'Kareena Dusseja',
        captionVariant: 'isdi-2',
        looseCaption: false,
        bottom16: false,
        topSet: false,
      },
      {
        image: {
          src: '/assets/images/schools/isdi/programs/b-des/fashion-communication-styling/projects/badri.png',
          width: 293,
          height: 319,
          alt: '',
        },
        text: 'Vaidahee, Vaibhavi,',
        captionVariant: 'isdi-2',
        looseCaption: false,
        bottom16: false,
        topSet: false,
      },
      {
        image: {
          src: '/assets/images/schools/isdi/programs/b-des/fashion-communication-styling/projects/5433.webp',
          width: 292,
          height: 364,
          alt: '',
        },
        text: 'Aarushi NC',
        captionVariant: 'isdi-2',
        looseCaption: false,
        bottom16: false,
        topSet: false,
      },
      {
        image: {
          src: '/assets/images/schools/isdi/programs/b-des/fashion-communication-styling/projects/att121.webp',
          width: 293,
          height: 319,
          alt: '',
        },
        text: 'Aarushi NC',
        captionVariant: 'isdi-2',
        looseCaption: false,
        bottom16: false,
        topSet: false,
      },
    ],
  ],
};
