/*
* "Student Projects in Motion" — index.php:2826-2891: the `.grid-gallery-flex` wall with the
 * `.insta-text.isdi-2` caption (transparent, a 6px #ec1376 rule under it) instead of the pink chip.
 */
export const isdiBdesFashionDesignProjects = {
  heading: 'Student Projects in Motion',
  sub: 'Where creativity meets momentum',
  columns: [
    [
      {
        image: {
          src: '/assets/images/schools/isdi/programs/b-des/fashion-design-technology/projects/fd-student-work-1.webp',
          width: 292,
          height: 520,
          alt: '',
        },
        text: 'Sahithi Chithumala',
        captionVariant: 'isdi-2',
        looseCaption: false,
        bottom16: false,
        topSet: false,
      },
      {
        image: {
          src: '/assets/images/schools/isdi/programs/b-des/fashion-design-technology/projects/anjali.webp',
          width: 292,
          height: 163,
          alt: '',
        },
        text: 'Anjali Oberoi',
        captionVariant: 'isdi-2',
        looseCaption: false,
        bottom16: false,
        topSet: true,
      },
      {
        image: {
          src: '/assets/images/schools/isdi/programs/b-des/fashion-design-technology/projects/fd-student-work-2.webp',
          width: 292,
          height: 520,
          alt: '',
        },
        text: 'Anjali Oberoi',
        captionVariant: 'isdi-2',
        looseCaption: false,
        bottom16: false,
        topSet: true,
      },
      {
        image: {
          src: '/assets/images/schools/isdi/programs/b-des/fashion-design-technology/projects/anushkav.webp',
          width: 292,
          height: 163,
          alt: '',
        },
        text: 'Anushka Vakeel',
        captionVariant: 'isdi-2',
        looseCaption: false,
        bottom16: false,
        topSet: true,
      },
    ],
    [
      {
        image: {
          src: '/assets/images/schools/isdi/programs/b-des/fashion-design-technology/projects/fd-student-work-3.webp',
          width: 299,
          height: 308,
          alt: '',
        },
        text: 'Tamanna Mittal',
        captionVariant: 'isdi-2',
        looseCaption: false,
        bottom16: false,
        topSet: false,
      },
      {
        image: {
          src: '/assets/images/schools/isdi/programs/b-des/fashion-design-technology/projects/fd-student-wwork-4.webp',
          width: 296,
          height: 382,
          alt: '',
        },
        text: 'Karishma Dora',
        captionVariant: 'isdi-2',
        looseCaption: false,
        bottom16: false,
        topSet: false,
      },
      {
        image: {
          src: '/assets/images/schools/isdi/programs/b-des/fashion-design-technology/projects/shania.webp',
          width: 292,
          height: 301,
          alt: '',
        },
        text: 'Shania Trehon',
        captionVariant: 'isdi-2',
        looseCaption: false,
        bottom16: false,
        topSet: false,
      },
      {
        image: {
          src: '/assets/images/schools/isdi/programs/b-des/fashion-design-technology/projects/fd-student-wwork-5.webp',
          width: 292,
          height: 373,
          alt: '',
        },
        text: 'Simran Khabrani',
        captionVariant: 'isdi-2',
        looseCaption: false,
        bottom16: false,
        topSet: false,
      },
    ],
    [
      {
        image: {
          src: '/assets/images/schools/isdi/programs/b-des/fashion-design-technology/projects/jaya.webp',
          width: 293,
          height: 163,
          alt: '',
        },
        text: 'Jaya Bhat',
        captionVariant: 'isdi-2',
        looseCaption: false,
        bottom16: true,
        topSet: false,
      },
      {
        image: {
          src: '/assets/images/schools/isdi/programs/b-des/fashion-design-technology/projects/fd-student-wwork-7.webp',
          width: 292,
          height: 520,
          alt: '',
        },
        text: 'Riya Mehta',
        captionVariant: 'isdi-2',
        looseCaption: false,
        bottom16: false,
        topSet: false,
      },
      {
        image: {
          src: '/assets/images/schools/isdi/programs/b-des/fashion-design-technology/projects/maher.webp',
          width: 293,
          height: 163,
          alt: '',
        },
        text: 'Maher Simar',
        captionVariant: 'isdi-2',
        looseCaption: false,
        bottom16: false,
        topSet: false,
      },
      {
        image: {
          src: '/assets/images/schools/isdi/programs/b-des/fashion-design-technology/projects/fd-student-wwork-6.webp',
          width: 292,
          height: 520,
          alt: '',
        },
        text: 'Meghana Bavaskar',
        captionVariant: 'isdi-2',
        looseCaption: false,
        bottom16: false,
        topSet: false,
      },
    ],
    [
      {
        image: {
          src: '/assets/images/schools/isdi/programs/b-des/fashion-design-technology/projects/fd-student-wwork-8.webp',
          width: 292,
          height: 364,
          alt: '',
        },
        text: 'Preethika Donapati',
        captionVariant: 'isdi-2',
        looseCaption: false,
        bottom16: false,
        topSet: false,
      },
      {
        image: {
          src: '/assets/images/schools/isdi/programs/b-des/fashion-design-technology/projects/shraddha.webp',
          width: 293,
          height: 319,
          alt: '',
        },
        text: 'Shraddha Jadhav',
        captionVariant: 'isdi-2',
        looseCaption: false,
        bottom16: false,
        topSet: false,
      },
      {
        image: {
          src: '/assets/images/schools/isdi/programs/b-des/fashion-design-technology/projects/anush.webp',
          width: 292,
          height: 364,
          alt: '',
        },
        text: 'Anushka Vakeel',
        captionVariant: 'isdi-2',
        looseCaption: false,
        bottom16: false,
        topSet: false,
      },
      {
        image: {
          src: '/assets/images/schools/isdi/programs/b-des/fashion-design-technology/projects/jayabhatttt.webp',
          width: 293,
          height: 319,
          alt: '',
        },
        text: 'Jaya Bhat',
        captionVariant: 'isdi-2',
        looseCaption: false,
        bottom16: false,
        topSet: false,
      },
    ],
  ],
};
