/*
* "Student Projects in Motion" — index.php:2826-2891: the `.grid-gallery-flex` wall with the
 * `.insta-text.isdi-2` caption (transparent, a 6px #ec1376 rule under it) instead of the pink chip.
 */
export const isdiBdesAnimationProjects = {
  heading: 'Student Projects in Motion',
  sub: 'Where creativity meets momentum',
  columns: [
    [
      {
        image: {
          src: '/assets/images/schools/isdi/programs/b-des/animation-vfx-gaming/projects/img_7716.webp',
          width: 292,
          height: 520,
          alt: '',
        },
        text: 'Liana Fernandes',
        captionVariant: 'isdi-2',
        looseCaption: false,
        bottom16: false,
        topSet: false,
      },
      {
        image: {
          src: '/assets/images/schools/isdi/programs/b-des/animation-vfx-gaming/projects/anish3.webp',
          width: 292,
          height: 163,
          alt: '',
        },
        text: 'Anish Kumar',
        captionVariant: 'isdi-2',
        looseCaption: false,
        bottom16: false,
        topSet: true,
      },
      {
        image: {
          src: '/assets/images/schools/isdi/programs/b-des/animation-vfx-gaming/projects/sarah3.webp',
          width: 292,
          height: 520,
          alt: '',
        },
        text: 'Sarah Xavier',
        captionVariant: 'isdi-2',
        looseCaption: false,
        bottom16: false,
        topSet: true,
      },
      {
        image: {
          src: '/assets/images/schools/isdi/programs/b-des/animation-vfx-gaming/projects/anish.webp',
          width: 292,
          height: 163,
          alt: '',
        },
        text: 'Anish Kumar',
        captionVariant: 'isdi-2',
        looseCaption: false,
        bottom16: false,
        topSet: true,
      },
    ],
    [
      {
        image: {
          src: '/assets/images/schools/isdi/programs/b-des/animation-vfx-gaming/projects/vfx-stu-work-3.webp',
          width: 299,
          height: 308,
          alt: '',
        },
        text: 'Savi Saxena Nigam',
        captionVariant: 'isdi-2',
        looseCaption: false,
        bottom16: false,
        topSet: false,
      },
      {
        image: {
          src: '/assets/images/schools/isdi/programs/b-des/animation-vfx-gaming/projects/sarah.webp',
          width: 292,
          height: 383,
          alt: '',
        },
        text: 'Sarah Xavier',
        captionVariant: 'isdi-2',
        looseCaption: false,
        bottom16: false,
        topSet: false,
      },
      {
        image: {
          src: '/assets/images/schools/isdi/programs/b-des/animation-vfx-gaming/projects/vfx-stu-work-4.webp',
          width: 292,
          height: 301,
          alt: '',
        },
        text: 'Sairaj Menon',
        captionVariant: 'isdi-2',
        looseCaption: false,
        bottom16: false,
        topSet: false,
      },
      {
        image: {
          src: '/assets/images/schools/isdi/programs/b-des/animation-vfx-gaming/projects/radhika.webp',
          width: 292,
          height: 383,
          alt: '',
        },
        text: 'Radhika Rane',
        captionVariant: 'isdi-2',
        looseCaption: false,
        bottom16: false,
        topSet: false,
      },
    ],
    [
      {
        image: {
          src: '/assets/images/schools/isdi/programs/b-des/animation-vfx-gaming/projects/liana.webp',
          width: 293,
          height: 163,
          alt: '',
        },
        text: 'Liana Fernandes',
        captionVariant: 'isdi-2',
        looseCaption: false,
        bottom16: true,
        topSet: false,
      },
      {
        image: {
          src: '/assets/images/schools/isdi/programs/b-des/animation-vfx-gaming/projects/vfx-stu-work-2.webp',
          width: 292,
          height: 520,
          alt: '',
        },
        text: 'Khushi Gapta',
        captionVariant: 'isdi-2',
        looseCaption: false,
        bottom16: false,
        topSet: false,
      },
      {
        image: {
          src: '/assets/images/schools/isdi/programs/b-des/animation-vfx-gaming/projects/abhay.webp',
          width: 293,
          height: 163,
          alt: '',
        },
        text: 'Abhay Krishna',
        captionVariant: 'isdi-2',
        looseCaption: false,
        bottom16: false,
        topSet: false,
      },
      {
        image: {
          src: '/assets/images/schools/isdi/programs/b-des/animation-vfx-gaming/projects/vfx-stu-work-5.webp',
          width: 292,
          height: 520,
          alt: '',
        },
        text: 'Savi Nigam',
        captionVariant: 'isdi-2',
        looseCaption: false,
        bottom16: false,
        topSet: false,
      },
    ],
    [
      {
        image: {
          src: '/assets/images/schools/isdi/programs/b-des/animation-vfx-gaming/projects/vfx-stu-work-7.webp',
          width: 292,
          height: 364,
          alt: '',
        },
        text: 'Savi Nigam',
        captionVariant: 'isdi-2',
        looseCaption: false,
        bottom16: false,
        topSet: false,
      },
      {
        image: {
          src: '/assets/images/schools/isdi/programs/b-des/animation-vfx-gaming/projects/vfx.png',
          width: 293,
          height: 319,
          alt: '',
        },
        text: 'Radhika Rane',
        captionVariant: 'isdi-2',
        looseCaption: false,
        bottom16: false,
        topSet: false,
      },
      {
        image: {
          src: '/assets/images/schools/isdi/programs/b-des/animation-vfx-gaming/projects/vfx-stu-work-8.webp',
          width: 292,
          height: 364,
          alt: '',
        },
        text: 'Sarah Xavier',
        captionVariant: 'isdi-2',
        looseCaption: false,
        bottom16: false,
        topSet: false,
      },
      {
        image: {
          src: '/assets/images/schools/isdi/programs/b-des/animation-vfx-gaming/projects/pawana.webp',
          width: 293,
          height: 319,
          alt: '',
        },
        text: 'Pawana Kumble',
        captionVariant: 'isdi-2',
        looseCaption: false,
        bottom16: false,
        topSet: false,
      },
    ],
  ],
};
