/*
* "Student Projects in Motion" — index.php:2826-2891: the `.grid-gallery-flex` wall with the
 * `.insta-text.isdi-2` caption (transparent, a 6px #ec1376 rule under it) instead of the pink chip.
 */
export const isdiBdesInteriorProjects = {
  heading: 'Student Projects in Motion',
  sub: 'Where creativity meets momentum',
  columns: [
    [
      {
        image: {
          src: '/assets/images/schools/isdi/programs/b-des/interior-design-built-environment/projects/id-stu-work-1.webp',
          width: 292,
          height: 520,
          alt: '',
        },
        text: 'Sania Kulkarni, Richa Shah, Khadijah Limdiwala',
        captionVariant: 'isdi-2',
        looseCaption: true,
        bottom16: false,
        topSet: false,
      },
      {
        image: {
          src: '/assets/images/schools/isdi/programs/b-des/interior-design-built-environment/projects/id-stu-work-2.webp',
          width: 292,
          height: 163,
          alt: '',
        },
        text: 'Daniya, Karishma, Ronak',
        captionVariant: 'isdi-2',
        looseCaption: true,
        bottom16: false,
        topSet: true,
      },
      {
        image: {
          src: '/assets/images/schools/isdi/programs/b-des/interior-design-built-environment/projects/id-stu-work-2-1.webp',
          width: 292,
          height: 520,
          alt: '',
        },
        text: 'Gurleen, Titiksha, Rosette',
        captionVariant: 'isdi-2',
        looseCaption: true,
        bottom16: false,
        topSet: true,
      },
      {
        image: {
          src: '/assets/images/schools/isdi/programs/b-des/interior-design-built-environment/projects/id-stu-work-2-2.webp',
          width: 292,
          height: 163,
          alt: '',
        },
        text: 'Titiksha Jadhav',
        captionVariant: 'isdi-2',
        looseCaption: false,
        bottom16: false,
        topSet: true,
      },
    ],
    [
      {
        image: {
          src: '/assets/images/schools/isdi/programs/b-des/interior-design-built-environment/projects/id-stu-work-3.webp',
          width: 299,
          height: 308,
          alt: '',
        },
        text: 'Geetika Bansal and Khushi Choksi',
        captionVariant: 'isdi-2',
        looseCaption: true,
        bottom16: false,
        topSet: false,
      },
      {
        image: {
          src: '/assets/images/schools/isdi/programs/b-des/interior-design-built-environment/projects/id-stu-work-4.webp',
          width: 296,
          height: 383,
          alt: '',
        },
        text: 'Biomimicry Design Studio',
        captionVariant: 'isdi-2',
        looseCaption: true,
        bottom16: false,
        topSet: false,
      },
      {
        image: {
          src: '/assets/images/schools/isdi/programs/b-des/interior-design-built-environment/projects/id-stu-work-2-3.webp',
          width: 292,
          height: 301,
          alt: '',
        },
        text: 'Karishma , Vidisha, Andrea, Saanvi, Rohit',
        captionVariant: 'isdi-2',
        looseCaption: true,
        bottom16: false,
        topSet: false,
      },
      {
        image: {
          src: '/assets/images/schools/isdi/programs/b-des/interior-design-built-environment/projects/id-stu-work-2-4.webp',
          width: 292,
          height: 383,
          alt: '',
        },
        text: 'Bhadar, Yashvi, Rasila',
        captionVariant: 'isdi-2',
        looseCaption: false,
        bottom16: false,
        topSet: false,
      },
    ],
    [
      {
        image: {
          src: '/assets/images/schools/isdi/programs/b-des/interior-design-built-environment/projects/id-stu-work-5.webp',
          width: 293,
          height: 163,
          alt: '',
        },
        text: 'Trisha Bachkaniwala',
        captionVariant: 'isdi-2',
        looseCaption: false,
        bottom16: true,
        topSet: false,
      },
      {
        image: {
          src: '/assets/images/schools/isdi/programs/b-des/interior-design-built-environment/projects/id-stu-work-6.webp',
          width: 292,
          height: 520,
          alt: '',
        },
        text: 'Arya Koli, Aashna Karia, Kajal Mistry, Sanvi Agarwal',
        captionVariant: 'isdi-2',
        looseCaption: true,
        bottom16: false,
        topSet: false,
      },
      {
        image: {
          src: '/assets/images/schools/isdi/programs/b-des/interior-design-built-environment/projects/id-stu-work-2-5.webp',
          width: 293,
          height: 163,
          alt: '',
        },
        text: 'Shifaan Zeri',
        captionVariant: 'isdi-2',
        looseCaption: false,
        bottom16: false,
        topSet: false,
      },
      {
        image: {
          src: '/assets/images/schools/isdi/programs/b-des/interior-design-built-environment/projects/id-stu-work-2-6.webp',
          width: 292,
          height: 520,
          alt: '',
        },
        text: 'Titiksha Mahajan',
        captionVariant: 'isdi-2',
        looseCaption: false,
        bottom16: false,
        topSet: false,
      },
    ],
    [
      {
        image: {
          src: '/assets/images/schools/isdi/programs/b-des/interior-design-built-environment/projects/id-stu-work-7.webp',
          width: 292,
          height: 364,
          alt: '',
        },
        text: 'Geetika Bansal and Khushi Choksi',
        captionVariant: 'isdi-2',
        looseCaption: true,
        bottom16: false,
        topSet: false,
      },
      {
        image: {
          src: '/assets/images/schools/isdi/programs/b-des/interior-design-built-environment/projects/id-stu-work-8.webp',
          width: 293,
          height: 319,
          alt: '',
        },
        text: 'Kajal Mistry',
        captionVariant: 'isdi-2',
        looseCaption: false,
        bottom16: false,
        topSet: false,
      },
      {
        image: {
          src: '/assets/images/schools/isdi/programs/b-des/interior-design-built-environment/projects/id-stu-work-2-7-1aa536.webp',
          width: 292,
          height: 364,
          alt: '',
        },
        text: 'Muhammad Zeri',
        captionVariant: 'isdi-2',
        looseCaption: false,
        bottom16: false,
        topSet: false,
      },
      {
        image: {
          src: '/assets/images/schools/isdi/programs/b-des/interior-design-built-environment/projects/id-stu-work-2-7.webp',
          width: 293,
          height: 319,
          alt: '',
        },
        text: 'Khushi, Kunal, Rishi, Shivani and Siddharth',
        captionVariant: 'isdi-2',
        looseCaption: true,
        bottom16: false,
        topSet: false,
      },
    ],
  ],
};
