/*
* "Student Projects in Motion" — index.php:2826-2891: the `.grid-gallery-flex` wall with the
 * `.insta-text.isdi-2` caption (transparent, a 6px #ec1376 rule under it) instead of the pink chip.
 */
export const isdiBdesHealthCareProjects = {
  heading: 'Student Projects in Motion',
  sub: 'Where creativity meets momentum',
  columns: [
    [
      {
        image: {
          src: '/assets/images/schools/isdi/programs/b-des/accessory-design-craft/projects/sp-2.webp',
          width: 292,
          height: 520,
          alt: '',
        },
        text: 'Vani Jain',
        captionVariant: 'isdi-2',
        looseCaption: false,
        bottom16: false,
        topSet: false,
      },
      {
        image: {
          src: '/assets/images/schools/isdi/programs/b-des/accessory-design-craft/projects/sp-4.webp',
          width: 292,
          height: 163,
          alt: '',
        },
        text: 'Amey Bardapurkar',
        captionVariant: 'isdi-2',
        looseCaption: false,
        bottom16: false,
        topSet: true,
      },
      {
        image: {
          src: '/assets/images/schools/isdi/programs/b-des/accessory-design-craft/projects/sp-1.webp',
          width: 292,
          height: 520,
          alt: '',
        },
        text: 'Atharva Jadhav',
        captionVariant: 'isdi-2',
        looseCaption: false,
        bottom16: false,
        topSet: true,
      },
      {
        image: {
          src: '/assets/images/schools/isdi/programs/b-des/accessory-design-craft/projects/arshia-anil.png',
          width: 292,
          height: 163,
          alt: '',
        },
        text: 'Arshia Anil',
        captionVariant: 'isdi-2',
        looseCaption: false,
        bottom16: false,
        topSet: true,
      },
    ],
    [
      {
        image: {
          src: '/assets/images/schools/isdi/programs/b-des/accessory-design-craft/projects/sp-3.webp',
          width: 299,
          height: 308,
          alt: '',
        },
        text: 'Surbhi Nagari',
        captionVariant: 'isdi-2',
        looseCaption: false,
        bottom16: false,
        topSet: false,
      },
      {
        image: {
          src: '/assets/images/schools/isdi/programs/b-des/accessory-design-craft/projects/manya-kamath.webp',
          width: 292,
          height: 382,
          alt: '',
        },
        text: 'Manya Kamath',
        captionVariant: 'isdi-2',
        looseCaption: false,
        bottom16: false,
        topSet: false,
      },
      {
        image: {
          src: '/assets/images/schools/isdi/programs/b-des/accessory-design-craft/projects/jay-pimpalkhare.webp',
          width: 292,
          height: 301,
          alt: '',
        },
        text: 'Jay Pimpalkhare',
        captionVariant: 'isdi-2',
        looseCaption: false,
        bottom16: false,
        topSet: false,
      },
      {
        image: {
          src: '/assets/images/schools/isdi/programs/b-des/accessory-design-craft/projects/ameya-kulkarni.webp',
          width: 292,
          height: 382,
          alt: '',
        },
        text: 'Ameya Kulkarni',
        captionVariant: 'isdi-2',
        looseCaption: false,
        bottom16: false,
        topSet: false,
      },
    ],
    [
      {
        image: {
          src: '/assets/images/schools/isdi/programs/b-des/accessory-design-craft/projects/trisha-bachkaniwala.webp',
          width: 293,
          height: 163,
          alt: '',
        },
        text: 'Trisha Bachkaniwala',
        captionVariant: 'isdi-2',
        looseCaption: false,
        bottom16: true,
        topSet: false,
      },
      {
        image: {
          src: '/assets/images/schools/isdi/programs/b-des/accessory-design-craft/projects/silaai.webp',
          width: 292,
          height: 520,
          alt: '',
        },
        text: 'Jinal Dharamshi',
        captionVariant: 'isdi-2',
        looseCaption: false,
        bottom16: false,
        topSet: false,
      },
      {
        image: {
          src: '/assets/images/schools/isdi/programs/b-des/accessory-design-craft/projects/rehaan-goregaokar.webp',
          width: 293,
          height: 163,
          alt: '',
        },
        text: 'Rehaan Goregaokar',
        captionVariant: 'isdi-2',
        looseCaption: false,
        bottom16: false,
        topSet: false,
      },
      {
        image: {
          src: '/assets/images/schools/isdi/programs/b-des/accessory-design-craft/projects/awakening.webp',
          width: 292,
          height: 520,
          alt: '',
        },
        text: 'Shreya Jangid',
        captionVariant: 'isdi-2',
        looseCaption: false,
        bottom16: false,
        topSet: false,
      },
    ],
    [
      {
        image: {
          src: '/assets/images/schools/isdi/programs/b-des/accessory-design-craft/projects/sailee-sanaye.webp',
          width: 292,
          height: 364,
          alt: '',
        },
        text: 'Sailee Sanaye',
        captionVariant: 'isdi-2',
        looseCaption: false,
        bottom16: false,
        topSet: false,
      },
      {
        image: {
          src: '/assets/images/schools/isdi/programs/b-des/accessory-design-craft/projects/amartya-garikapati.webp',
          width: 293,
          height: 319,
          alt: '',
        },
        text: 'Amartya Garikapati',
        captionVariant: 'isdi-2',
        looseCaption: false,
        bottom16: false,
        topSet: false,
      },
      {
        image: {
          src: '/assets/images/schools/isdi/programs/b-des/accessory-design-craft/projects/tisya.webp',
          width: 292,
          height: 364,
          alt: '',
        },
        text: 'Tisya Jain',
        captionVariant: 'isdi-2',
        looseCaption: false,
        bottom16: false,
        topSet: false,
      },
      {
        image: {
          src: '/assets/images/schools/isdi/programs/b-des/accessory-design-craft/projects/tanishka-shah-work.webp',
          width: 293,
          height: 319,
          alt: '',
        },
        text: 'Tanishka Shah',
        captionVariant: 'isdi-2',
        looseCaption: false,
        bottom16: false,
        topSet: false,
      },
    ],
  ],
};
